// <auto-generated />
using System;
using GeoImager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeoImager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210315135239_ProfileMigration")]
    partial class ProfileMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeoImager.Data.Models.ImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageModel");
                });

            modelBuilder.Entity("GeoImager.Data.Models.ProfileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrivateProfile")
                        .HasColumnType("bit");

                    b.Property<int?>("UserBackgroundImageId")
                        .HasColumnType("int");

                    b.Property<int?>("UserProfileImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserBackgroundImageId");

                    b.HasIndex("UserProfileImageId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("GeoImager.Data.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeoImager.Data.Models.ProfileModel", b =>
                {
                    b.HasOne("GeoImager.Data.Models.ImageModel", "UserBackgroundImage")
                        .WithMany()
                        .HasForeignKey("UserBackgroundImageId");

                    b.HasOne("GeoImager.Data.Models.ImageModel", "UserProfileImage")
                        .WithMany()
                        .HasForeignKey("UserProfileImageId");

                    b.Navigation("UserBackgroundImage");

                    b.Navigation("UserProfileImage");
                });
#pragma warning restore 612, 618
        }
    }
}
